"""mentisq sessions messages settings

Revision ID: 31df1b0725a5
Revises: d05275379eac
Create Date: 2026-08-29 13:40:45.235664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31df1b0725a5'
down_revision: Union[str, None] = 'd05275379eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('mentisq_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('context_topic_id', sa.Integer(), nullable=True),
    sa.Column('context_question_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['context_question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['context_topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentisq_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentisq_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentisq_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('mentisq_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['mentisq_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentisq_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentisq_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentisq_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentisq_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentisq_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_mentisq_messages_created_at'))

    op.drop_table('mentisq_messages')
    with op.batch_alter_table('mentisq_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentisq_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_mentisq_sessions_created_at'))

    op.drop_table('mentisq_sessions')
    op.drop_table('settings')
    # ### end Alembic commands ###
