"""practice questions, skill tags, attempts

Revision ID: 80260ce18415
Revises: d04266680a3d
Create Date: 2026-08-29 12:43:35.434198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80260ce18415'
down_revision: Union[str, None] = 'd04266680a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_tags_name'), ['name'], unique=True)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('answer_schema', sa.JSON(), nullable=False),
    sa.Column('worked_solution', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_topic_id'), ['topic_id'], unique=False)

    op.create_table('question_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('submitted_answer', sa.JSON(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('mentisq_used', sa.Boolean(), nullable=False),
    sa.Column('solution_viewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('question_skill_tags',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('skill_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_tag_id'], ['skill_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'skill_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_skill_tags')
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_created_at'))

    op.drop_table('question_attempts')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic_id'))

    op.drop_table('questions')
    with op.batch_alter_table('skill_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_tags_name'))

    op.drop_table('skill_tags')
    # ### end Alembic commands ###
