"""content tree, lecture content, topic views

Revision ID: d04266680a3d
Revises: 68501efbe171
Create Date: 2026-08-29 12:14:19.662778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04266680a3d'
down_revision: Union[str, None] = '68501efbe171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('year_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('syllabus_region', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_level_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['year_level_id'], ['year_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_year_level_id'), ['year_level_id'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_subject_id'), ['subject_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_topics_unit_id'), ['unit_id'], unique=False)

    op.create_table('lecture_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lecture_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lecture_content_topic_id'), ['topic_id'], unique=True)

    op.create_table('topic_prerequisites',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'prerequisite_topic_id')
    )
    op.create_table('topic_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_views_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_views_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_views_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_topic_views_topic_id'))
        batch_op.drop_index(batch_op.f('ix_topic_views_created_at'))

    op.drop_table('topic_views')
    op.drop_table('topic_prerequisites')
    with op.batch_alter_table('lecture_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lecture_content_topic_id'))

    op.drop_table('lecture_content')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_unit_id'))
        batch_op.drop_index(batch_op.f('ix_topics_slug'))

    op.drop_table('topics')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_subject_id'))

    op.drop_table('units')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_year_level_id'))

    op.drop_table('subjects')
    op.drop_table('year_levels')
    # ### end Alembic commands ###
