"""seed ingest: slug natural keys

Revision ID: d05275379eac
Revises: 80260ce18415
Create Date: 2026-08-29 12:55:15.960542

Adds a `slug` column to `year_levels`, `subjects`, `units`, and `questions` so
the seed ingest (ticket 05) can upsert every entity by a stable natural key,
matching the existing `topics.slug`. Nullable + unique: nullable so the column
adds cleanly to a populated database (SQLite allows many NULLs under a unique
index), unique so a non-null slug identifies at most one row. The ingest is the
only writer of these tables in Phase 1 and always sets it.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05275379eac'
down_revision: Union[str, None] = '80260ce18415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_questions_slug'), ['slug'], unique=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_subjects_slug'), ['slug'], unique=True)

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_units_slug'), ['slug'], unique=True)

    with op.batch_alter_table('year_levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_year_levels_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('year_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_year_levels_slug'))
        batch_op.drop_column('slug')

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_slug'))
        batch_op.drop_column('slug')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_slug'))
        batch_op.drop_column('slug')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
